import CmsNavbar from "../components/CmsNavbar"
import Provider from "../utils/Provider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
        <body>
          <CmsNavbar />
          {children}
        </body>
      </Provider>

    </html>
  )
}
